# Generated by Django 5.1.1 on 2024-10-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_product_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prouct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
    ]
