# Generated by Django 5.1.1 on 2024-10-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_set_once',
            field=models.BooleanField(default=False),
        ),
    ]
