# Generated by Django 5.1.1 on 2024-10-03 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_profile_is_completed_profile_role_set_once'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
