# Generated by Django 5.1.1 on 2024-10-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_sellerprofile_profile_photo_alter_sellerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_code',
            field=models.CharField(blank=True, choices=[('011', 'First Bank of Nigeria'), ('044', 'Access Bank'), ('058', 'Guaranty Trust Bank'), ('214', 'Unity Bank'), ('221', 'Stanbic IBTC Bank'), ('232', 'Sterling Bank'), ('033', 'United Bank for Africa'), ('035', 'Wema Bank'), ('082', 'Keystone Bank'), ('101', 'Providus Bank'), ('102', 'Suntrust Bank'), ('103', 'Titan Trust Bank'), ('232', 'Sterling Bank'), ('100', 'Opay'), ('50211', 'Kuda Bank'), ('560', 'Paga'), ('076', 'Polaris Bank'), ('070', 'Fidelity Bank'), ('057', 'Zenith Bank'), ('068', 'Standard Chartered Bank')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
