# Generated by Django 5.1.1 on 2024-10-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
