# Generated by Django 5.1.1 on 2024-10-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_buyerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
