# Generated by Django 5.1.1 on 2024-10-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_buyerprofile_address_buyerprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Cart',
            new_name='cart',
        ),
    ]
